gText_Birch_Welcome::
	.string "Based on the fable:\n"
	.string "The Wolves & the Sheep\p"
	.string "A pack of Wolves lurked near the\n"
	.string "Sheep pasture.\p"
	.string "But the Dogs kept them all at a\n"
	.string "respectful distance,\p"
	.string "and the Sheep grazed in perfect\n"
	.string "safety.\p"
	.string "But now the Wolves thought of a\n"
	.string "plan to trick the Sheep.\p"
	.string "“Why is there always this hostility\n"
	.string "between us?” they said.\p"
	.string "“If it were not for those Dogs who are\n"
	.string "always stirring up trouble,\p"
	.string "I am sure we should get along\n"
	.string "beautifully.\p"
	.string "Send them away and you will see what\n"
	.string "good friends we shall become.”\p"
	.string "The Sheep were easily fooled.\p"
	.string "They persuaded the Dogs to go away,\p"
	.string "and that very evening the Wolves\n"
	.string "had the grandest feast of their lives.\p"
	.string "{COLOR RED}Do not give up friends for foes.{COLOR DARK_GRAY}\p"
	.string "$"
	
gText_Birch_MainSpeech::
	.string "“Why is there always this hostility\n"
	.string "between us?” they said.\p"
	.string "“If it were not for those Dogs who are\n"
	.string "always stirring up trouble,\p"
	.string "I am sure we should get along\n"
	.string "beautifully.\p"
	.string "Send them away and you will see what\n"
	.string "good friends we shall become.”\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "The Sheep were easily fooled.\p"
	.string "They persuaded the Dogs to go away,\p"
	.string "and that very evening the Wolves\n"
	.string "had the grandest feast of their lives.\p"
	.string "{COLOR RED}Do not give up friends for foes.{COLOR DARK_GRAY}\p"
	.string "$"
